---

#safe(ish) defaults
server_name: gitlab.example.org
private_network: 192.168.0.*
private_network_cidr: 192.168.0.0/24


image_name: "CentOS-7.0"

server_flavor: io.70GB
runner_flavor: io.70GB

ansible_user: cloud-user
gitlab_ssh_port: 10022