---

#safe(ish) defaults
server_name: gitlab.example.org
private_network: 192.168.0.*
private_network_cidr: 192.168.0.0/24


image_name: "CentOS-7.0"

server_flavor: io.70GB

runner_vms:
  centos:
    flavor: "io.70GB"
    image: "CentOS-7.0"

ansible_user: cloud-user
gitlab_control_port: 10022

#controls creating extra volumes and possibly other things in the future
environment_type: test

# these default to yes but can be set to no to avoid creating extra instances
# or if e.g. backup server is in a different domain (in which case an entry in hosts is required)
create_runner: yes
create_backup: yes

