---

#safe(ish) defaults
server_name: gitlab.example.org
private_network: 192.168.0.*
private_network_cidr: 192.168.0.0/24


image_name: "CentOS-7"

server_flavor: io.70GB

runner_vms:
  centos:
    flavor: "io.70GB"
    image: "CentOS-7.0"

ansible_user: cloud-user
gitlab_control_port: 10022

#controls creating extra volumes and possibly other things in the future
environment_type: test

# runner creation in this playbook is deprecated and will be removed soon.
# if you need runners use a separate playbook, e.g.
# https://github.com/coderefinery/openstack-gitlab-runner
create_runner: no
# if e.g. backup server is in a different domain (in which case an entry in hosts is required)
# this can be disabled
create_backup: yes

