---

- name: create backup
  os_security_group:
    name: "{{ gitlab_name }}-backup-sg"
    description: "[ansible] automatically created security group for {{ gitlab_name  }} backup"
  register: admin_security_group

- name: create an extra volume for backups
  os_volume:
    size: 200 # gb
    display_name: "{{ gitlab_name }}-backups"
    display_description: "[ansible] volume for server {{ gitlab_name }}-backup"
  register: data_volume

- name: Create the gitlab backup server
  os_server:
    name: "{{ gitlab_name }}-backup"
    state: present
    image: "{{ image_name }}"
    key_name: "{{ keypair_name }}"
    timeout: 200
    flavor: "{{ server_flavor }}"
    auto_ip: no
    security_groups:
      - "{{ gitlab_name }}-common-group"
      - "{{ gitlab_name }}-ssh-from-local"
  register: backup_server

- name: attach backup volume
  os_server_volume:
    state: present
    server: "{{ gitlab_name }}-backup"
    volume:  "{{ gitlab_name }}-backups"
    device: "{{ backup_device }}"

- name: add backup_server to inventory
  add_host:
    name: gitlab-backup
    groups: backup
    ansible_ssh_port: 22
    ansible_ssh_user: cloud-user

