- name: create ssh from csc security group
  os_security_group:
    name: "{{ gitlab_name }}-ssh-from-csc"
    description: "[ansible] automatically created security group for {{ gitlab_name  }}"
  register: admin_security_group

- name: security group for SSH from CSC
  os_security_group_rule:
    security_group: "{{ gitlab_name }}-ssh-from-csc"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 193.166.85.0/24

- name: security group for SSH from CSC
  os_security_group_rule:
    security_group: "{{ gitlab_name }}-ssh-from-csc"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 193.166.2.0/24

- name: security group for SSH from CSC
  os_security_group_rule:
    security_group: "{{ gitlab_name }}-ssh-from-csc"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 193.166.1.0/24
