---
- name: create volumes
  os_volume:
    size: "{{ item.size }}"
    display_name: "{{ item.name }}"
    display_description: "[ansible] volume for server {{ gitlab_name }}"
  with_items: "{{ extra_volumes }}"

- name: Create the actual gitlab server
  os_server:
    name: "{{ gitlab_name }}"
    state: present
    image: "{{ image_name }}"
    key_name: "{{ keypair_name }}"
    timeout: 200
    flavor: "{{ server_flavor }}"
    #auto_ip: yes
    security_groups:
      - "{{ gitlab_name }}-external-sg"
      - "{{ gitlab_name }}-internal-sg"
    floating_ips:
      - "{{ public_ip }}"

  register: gitlab_server

- name: attach volumes
  os_server_volume:
    state: present
    server: "{{ gitlab_name }}"
    volume: "{{ item.name }}"
    device: "{{ item.device }}"
  with_items: "{{ extra_volumes }}"

- name: add gitlab_server
  add_host:
    name: gitlab
    groups: gitlab-docker
    ansible_ssh_host: "{{ gitlab_server.openstack.interface_ip }}"
    ansible_ssh_port: 22
    ansible_ssh_user: cloud-user
    private_v4: "{{ gitlab_server.openstack.private_v4 }}"
