- name: create admin access security group
  os_security_group:
    name: "{{ gitlab_name }}-external-sg"
    description: "[ansible] automatically created security group for {{ gitlab_name  }}"
  register: admin_security_group

- name: security group for SSH to_host
  os_security_group_rule:
    security_group: "{{ gitlab_name }}-external-sg"
    protocol: tcp
    port_range_min: "{{ item.port_range_min }}"
    port_range_max: "{{ item.port_range_min }}"
    remote_ip_prefix: "{{ item.remote_ip_prefix }}"
  with_items: "{{ firewall_rules }}"

- name: create internal security group between instances
  os_security_group:
    name: "{{ gitlab_name }}-internal-sg"
    description: "[ansible] automatically created security group for {{ gitlab_name  }}"
  register: common_security_group


- name: security group for things internal to parts of the deployment
  os_security_group_rule:
    security_group: "{{ gitlab_name }}-internal-sg"
    protocol: "{{ item }}"
    remote_group: "{{ common_security_group.secgroup.id }}"
  with_items:
    - "tcp"
    - "udp"
    - "icmp"

