---

- name: assert things about variables
  assert:
    that:
      - "keypair_name is defined"
      - "server_fqdn is defined"
      - "network_id is defined"
      - "public_ip is defined"
      - "gitlab_name is defined"
      - "ansible_user is defined"
      - "backup_device is defined"
      - "extra_volumes is defined"

- name: add keypair
  os_keypair:
    name: "{{ keypair_name }}"
    public_key:  "{{ deployment_ssh_pubkey }}"
  register: keypair
  when: deployment_ssh_pubkey is defined

- include: create_sg.yml

- include: create_gitlab.yml

- include: create_backup.yml
  when: create_backup

- include: create_runner.yml
  when: runner_registration_token|default("") != "" and create_runner

- name: pause for 10 seconds to let cloud-init work it's magic if backup and runner weren't created
  pause:
    seconds: 10
  when: not create_runner and not create_backup

- name: add ssh alias for forwarding to local config
  blockinfile:
    dest: ssh.cfg
    backup: no
    mode: 0700
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK for cr-gitlab"
    block: |
      Host {{ server_fqdn }}
      HostName {{ gitlab_server.openstack.interface_ip }}
      User {{ ansible_user }}
      ControlMaster auto
      ControlPath ~/.ssh/ansible-%r@%h:%p
      ControlPersist 5m

- name: add gitlab
  blockinfile:
    dest:  "ssh.{{ gitlab_name }}.cfg"
    backup: no
    mode: 0700
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK for cr-gitlab-proper"
    block: |
      Host gitlab
      HostName {{ gitlab_server.openstack.interface_ip }}
      User {{ ansible_user }}
      Port {{ gitlab_control_port }}

- name: add ssh alias to local ssh config
  blockinfile:
    dest:  "ssh.{{ gitlab_name }}.cfg"
    backup: no
    mode: 0700
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK for cr-gitlab-backup"
    block: |
      Host gitlab-backup
      HostName {{ backup_server.openstack.private_v4 }}
      User {{ ansible_user }}
      ProxyCommand ssh -p {{ gitlab_control_port }} -W %h:%p {{ ansible_user }}@{{ gitlab_server.openstack.interface_ip }}
  when: create_backup

- name: add ssh alias to local ssh config
  blockinfile:
    dest:  "ssh.{{ gitlab_name }}.cfg"
    backup: no
    mode: 0700
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK for cr-gitlab-runner"
    block: |
      Host gitlab-runner
      HostName {{ gitlab_runner.openstack.private_v4 }}
      User {{ ansible_user }}
      ProxyCommand ssh -p {{ gitlab_control_port }} -W %h:%p {{ ansible_user }}@{{ gitlab_server.openstack.interface_ip }}
  when: create_runner