- name: pull the image
  docker_image:
    name: "gitlab/gitlab-ce:{{ gitlab_tag }}"
  become: True

- name: start the container
  docker_container:
    name: gitlab
    image: "gitlab/gitlab-ce:{{ gitlab_tag }}"
    state: started
    restart_policy: always
    ports:
      - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:80:80"
      - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:443:443"
      - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ gitlab_ssh_port }}:22"
    volumes:
      - "/srv/gitlab/config:/etc/gitlab:Z"
      - "/srv/gitlab/logs:/var/log/gitlab:Z"
      - "/srv/gitlab/data:/var/opt/gitlab:Z"
      - "/srv/gitlab/data:/var/opt/gitlab:Z"
      - "/srv/gitlab/config/backups:/secret/gitlab/backups:Z"
  become: True

